### ISSUE TITLE
Timeslots nachbuchen

### ISSUE THREAD

**Issue by bmarcouly** [dev-viinz/stempeluhr#5]
Als Anwender möchte ich einen (vergessenen) Timeslot für einen Tag in der Vergangenheit nachbuchen können.

**Comment by dev-viinz** [comment]
@bmarcouly feature ist auf https://preview.justclockit.com/ live
anmelden geht mit:
```
spam@test
123
```

**Comment by bmarcouly** [comment]
FYI: Ich habe eine Mail bekommen 👍

**Comment by bmarcouly** [comment]
Beim Hinzufügen einer neuen Buchung wird nicht geprüft, ob die neue Buchung in das Zeitfenster bestehender Buchungen hineinragt.

![image](https://github.com/dev-viinz/stempeluhr/assets/49025465/72d8382f-9766-4cc7-90c7-12beadd591ac)

Sollten der Check-Out mal nach 0:00 erfolgen, also am nächsten Tag, läßt sich dass mit der aktuellen Implementierung nicht darstellen. Ist aber ggf. ein extra Featurerequest, da ich auch nicht weiß, ob es grundsätzlich möglich wäre eine Buchung über die Tagesgrenze laufen zu lassen.

Feedback lieber im Issue oder im PR?

**Comment by dev-viinz** [comment]
Ich würde Feedback spezifisch zur implementation im PR lassen, ist aber bei dem Projekt jetzt nicht entscheidend wenn's mal anders ist :)

**Comment by dev-viinz** [comment]
> Sollten der Check-Out mal nach 0:00 erfolgen, also am nächsten Tag, läßt sich dass mit der aktuellen Implementierung nicht darstellen. Ist aber ggf. ein extra Featurerequest, da ich auch nicht weiß, ob es grundsätzlich möglich wäre eine Buchung über die Tagesgrenze laufen zu lassen.

aktuell ist es nicht vorgesehen über tagesgrenzen hinweg zu buchen
