### ISSUE TITLE
Pausen automatisch buchen

### ISSUE THREAD

**Issue by bmarcouly** [dev-viinz/stempeluhr#6]
Als Anwender möchte ich, dass Pausen automatisch verbucht werden, wenn es am Tag nur einen "Check-In" und nur einen "Check-out" gibt.

- [ ] 30 min ab einer Arbeitszeit von 6h
- [ ] 45 min ab einer Arbeitszeit von 9h

Erweiterte Anforderung:
Sollte es mehr als einen gebuchten Timeslots am Tag geben, sollen die Zeiten zwischen den Timeslots summiert die erforderliche Pausenzeit ergeben und andernfalls die Pausenzeit, wie ober beschrieben, aufgefüllt werden.

**Comment by dev-viinz** [comment]
@bmarcouly #22 ist bereit zur review, ich bin mir unsicher wie es angezeigt werden soll, aber so klappt es eigentlich ganz gut :)

**Comment by bmarcouly** [comment]
@dev-viinz Ich habe noch keinen Zugang zur Testversion (oder ich habe ihn vergessen).

**Comment by dev-viinz** [comment]
@bmarcouly bleibe genau gleich wie hier https://github.com/dev-viinz/stempeluhr/issues/5#issuecomment-1716091469 :)

**Comment by bmarcouly** [comment]
Scheint so zu passen

![image](https://github.com/dev-viinz/stempeluhr/assets/49025465/8268c904-c720-4d5b-8c79-7fdf364745e1)
